### ISSUE TITLE
single build image link throws server error

### ISSUE THREAD

**Issue by dajohnso** [aeolusproject/conductor#379]
Click on a providers build link and this exception is thrown... looks to be related to image_version_id"=>"" 

```
Started POST "/tim/target_images?target_image%5Bimage_version_id%5D=&target_image%5Bprovider_type_id%5D=1" for 10.10.60.29 at 2013-01-25 14:04:05 -0500
Processing by Tim::TargetImagesController#create as HTML
  Parameters: {"authenticity_token"=>"/zAVCaUlXuWiSbXEzOHWbi8pJEAYjCnKR+mGvSySfcE=", "target_image"=>{"image_version_id"=>"", "provider_type_id"=>"1"}}
  ^[[1m^[[35mUser Load (0.4ms)^[[0m  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
  ^[[1m^[[36mPermissionSession Load (0.2ms)^[[0m  ^[[1mSELECT "permission_sessions".* FROM "permission_sessions" WHERE "permission_sessions"."id" = $1 LIMIT 1^[[0m  [["id", 1]]
undefined method `base_image' for nil:NilClass
backtrace follows
/home/test/w1/conductor/src/app/decorators/models/tim/target_image_decorator.rb:50:in `base_image'
        /home/test/w1/conductor/src/app/decorators/controllers/tim/target_images_controller_decorator.rb:54:in `check_create_permission'
        /home/test/w1/conductor/src/bundle/ruby/1.9.1/bundler/gems/rails-63970dc7db27/activesupport/lib/active_support/callbacks.rb:484:in `_run__3307795209061993473__process_action__2743244427345993041__callbacks'
        /home/test/w1/conductor/src/bundle/ruby/1.9.1/bundler/gems/rails-63970dc7db27/activesupport/lib/active_support/callbacks.rb:405:in `__run_callback'
        /home/test/w1/conductor/src/bundle/ruby/1.9.1/bundler/gems/rails-63970dc7db27/activesupport/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
        /home/test/w1/conductor/src/bundle/ruby/1.9.1/bundler/gems/rails-63970dc7db27/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /home/test/w1/conductor/src/bundle/ruby/1.9.1/bundler/gems/rails-63970dc7db27/actionpack/lib/abstract_controller/callbacks.rb:17:in `process_action'
        /home/test/w1/conductor/src/bundle/ruby/1.9.1/bundler/gems/rails-63970dc7db27/actionpack/lib/action_controller/metal/rescue.rb:29:in `process_action'
```

**Comment by n1zyy** [comment]
I believe this is a bug I introduced with the single 'Build' link (versus the 'Build All' link).
